-- 코드를 입력하세요
SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH , U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
    FROM ONLINE_SALE O
    LEFT JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
    WHERE U.GENDER IS NOT NULL
    GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')), U.GENDER
    ORDER BY YEAR, MONTH, GENDER

-- SELECT *
-- FROM ONLINE_SALE O
--     LEFT JOIN USER_INFO U
--     ON O.USER_ID = U.USER_ID
--     WHERE U.GENDER IS NULL

-- SELECT COUNT(*) FROM ONLINE_SALE