-- -- 코드를 입력하세요

-- SELECT to_number(TO_CHAR(START_DATE, 'MM')) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- GROUP BY TO_CHAR(START_DATE, 'MM');

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE EXTRACT(MONTH FROM START_DATE) >= 8 AND EXTRACT(MONTH FROM START_DATE) <= 10 AND CAR_ID IN (
        SELECT CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE EXTRACT(MONTH FROM START_DATE) >= 8 AND EXTRACT(MONTH FROM START_DATE) <= 10
            GROUP BY CAR_ID
            HAVING COUNT(*) >= 5)
    GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
    ORDER BY MONTH, CAR_ID DESC
